[workspace]
members = [
    'node',
    'pallets/celer-pay',
    'pallets/celer-pay/rpc',
    'pallets/celer-pay/rpc/runtime-api',
    'pallets/mock-boolean-condition',
    'pallets/mock-numeric-condition',
    'runtime',
]
[profile.release]
panic = 'unwind'